### ISSUE TITLE
Applying the script to Sci-Hub?

### ISSUE THREAD

**Issue by DonaldTsang** [ashwinvis/greasyfork#3]
It seems that none of the RG scripts don't do Sci-Hub, which is annoying.
- https://greasyfork.org/en/scripts/21924-rgdoi
- https://greasyfork.org/en/scripts/10602-redrem
- https://greasyfork.org/en/scripts/39256-rgdoi

Also, it seems that none of them support SemanticScholar-to-DOI/Sci-Hub.
So how could this be done?

Bonus: adding some of the features to https://greasyfork.org/en/scripts/370246-sci-hub-button

**Comment by ashwinvis** [comment]
1. This is beyond the intended scope of this userscript. Not saying this is impossible.
2.  If you rely on converting DOI requests, use an extension like [Redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector/)

**Comment by ashwinvis** [comment]
If you really want to do it via an userscript, modify the hyperlink here:

https://github.com/ashwinvis/userscripts/blob/38c43119455cbf755d8eda21fcaf930366d0a803/RGdoi.user.js#L48
